import type { Metadata } from "next";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import ReactQueryProvider from "./utils/_Provider";
import { MyProvider } from "./utils/_ContextProvider";

export const metadata: Metadata = {
  title: "React Hook Forms",
  description: "Generated by amin mousavi",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <MyProvider>
          <ReactQueryProvider>
            <Header />
            {children}
            <Footer />
          </ReactQueryProvider>
        </MyProvider>
      </body>
    </html>
  );
}
